[Hypr-GamepadStayAwake]
description="A plugin that resets the idle timer on controller button events"
version = "1.0"
authors = ["Mecso"]
output = "zig-out/lib/libhypr-gamepadstayawake.so"
build = [
    "zig build -Drelease"
]
